### PR TITLE
Add the percentage of collisions not detected by the app, due to protocol limits or hw/sw bugs

### LINKED ISSUE #20: Add a select option to choose the percentage of failure in the collisions detected by the app
**Scenario 1**:
Choose the percentage of collisions detected by the app.
As a user of the application,
When I choose 10% of app failure in the select,
Then I run the simulation but just 90% of the collisions among two balls are notified by the app.

This scenario shows the relevance of a well developed and tested app, because a bad one would jeopardise the diffusion of the app.

### PR DESCRIPTION
**Pull request by gioid**
This is a porting of the logic that I developed few days ago in my fork (previously to this repository).

### CODE REVIEW

File: src/Ball.js [hunk 1]
```diff
@@ -127,7 +129,8 @@ export class Ball {
   }
 
   isAwareToBeInfected (otherBall) {
-    return this.hasAppInstalled && otherBall.hasAppInstalled
+    return this.hasAppInstalled && otherBall.hasAppInstalled &&
+      this.sketch.random(100) >= this.appFailurePercentage
```
Comment (brushtyler) [inline src/Ball.js:133]: consider to store this boolean value as Ball member variable in place of `appFailurePercentage`.
If in the future we will reuse the function in a different part of the code we may get wrong results (different awareness).

File: src/app.js [hunk 2]
```diff
@@ -31,6 +31,7 @@ export const canvas = new window.p5(sketch => { // eslint-disable-line
   const startBalls = () => {
     let id = 0
     const peopleWithAppInPercentage = document.getElementById('app_users')
+    const appFailurePercentage = document.getElementById('app_failures').value
```
Comment (brushtyler) [inline src/app.js:34]: Consider to use `appFailuresElement` you defined in `dom.js`.
I know the other variables around it still use `document.getElementById(...)` even if defined in `dom.js`, but we should stop this practice someday :)

File: src/Ball.js (hunk 1 above)
Comment (gioid) [reply src/Ball.js:133]: I don't think it would be the same, because each collision should be affected by a different shot: sometimes the app could work, sometimes doesn't. Am I right?

Comment (brushtyler) [reply src/Ball.js:133]: I understand your point and generally speaking you're right, the app failure must be re-evaluated at each collision. 

BTW, this opens a new point:
the code invokes the isAwareToBeInfected just once per ball (look few lines above, if the ball's state is `well` only).
Is this the expected behavior? The ball should re-check for awareness every time it collides with another infected ball. Otherwise, if the first time the app fails, the ball will continue to move even after any next collision with an infected ball (the app may work the next times).

But we can open a new issue, so I would accept the current behavior w/o any objection.

**Review by brushtyler — APPROVED** [review]
